# Numpy Arrays
## Topics
* list
    * list into array
    * lists or list of lists to numpy range
* methods in numpy
    * arange
    * zeros
    * ones
    * linspace
    * eye
* random numbers
    * Uniform distribution
    * Standard normal distribution or Gaussian
    * Random integers from a low to a high
* reshape
* max, min, argmax, armin
* shape
* data type
* indexing and selection
* matrix
    * double bracket
    * comma single bracket
* conditional selection
* Numpy operations
    * array with array
    * array with scalars
    * universal array functions
        * sqrt
        * exp
        * max, min
        * sin
        * log
        * sum
        * std
* axis

## List

In [12]:
my_list=[1,2,3]
my_list

[1, 2, 3]

### * list into array

In [2]:
import numpy as np
arr = np.array(my_list)
arr

array([1, 2, 3])

### * lists or list of lists to numpy range

In [3]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Methods in numpy

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [8]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [10]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [11]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random Numbers

In [14]:
# Random samples from a uniform distribution
np.random.rand(5)

array([ 0.13534039,  0.33382032,  0.70831079,  0.7450565 ,  0.07811466])

In [15]:
np.random.rand(3,3)

array([[ 0.68618906,  0.93249294,  0.19554805],
       [ 0.87067536,  0.17527091,  0.70417521],
       [ 0.21333613,  0.01563835,  0.18599406]])

In [16]:
# Samples from the standard normal distribution or gaussian
np.random.randn(3)

array([-0.72095391, -0.37764026,  0.17800131])

In [17]:
np.random.randn(2,2)

array([[-0.01664246, -0.51278002],
       [-0.29238524, -0.97490852]])

In [18]:
# Random integers from a low to a high
np.random.randint(1,100)

8

In [19]:
np.random.randint(1,100,10)

array([ 3, 25, 92, 25, 52, 95, 47, 16, 63, 27])

## Reshape

In [21]:
arr = np.arange(25)
print(arr)
arr.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## max, min, argmax, argmin

In [22]:
ranarr = np.random.randint(1,100,10)
ranarr

array([40, 33, 82, 22, 29, 75,  6, 42, 71, 16])

In [23]:
ranarr.max()

82

In [24]:
ranarr.min()

6

In [25]:
ranarr.argmax()

2

In [26]:
ranarr.argmin()

6

## Shape

In [28]:
arr.shape

(25,)

## Data type

In [29]:
arr.dtype

dtype('int32')