# NumPy Arrays

In [6]:
my_list = [1,2,3]

In [8]:
my_list # just get a python list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [9]:
arr # casting a normal Python list into an array

array([1, 2, 3])

In [10]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_mat) # casting normal Python lists or list of lists to numpy range

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10) # works just as Python's own range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,11,2)  #간격 표시

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [73]:
np.zeros((5,5))    # (()) 가 두 개임에 유의

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [18]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [19]:
np.linspace(0,5,10) # get 10 evenly spaced points between zero to five

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

식이 길어져서 two dimensional로 보일 수 있으나,
위에 np.ones와 같이 bracket이 두개여야 two-dimensional
하나면 one-dimensional이 길어서 줄바꿈된 것

### linspace
linspace will take in the third argument as the number of points you want
### arange
arange will take in that argument as the step size you want

---
# Identity Matrix

In [20]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

---
# Random Numbers

#### Random Samples from a Uniform Distribution

In [22]:
np.random.rand(5) 

array([ 0.87175959,  0.37204974,  0.21533251,  0.95315544,  0.24252097])

In [24]:
np.random.rand(3,3)

array([[ 0.30903595,  0.33441309,  0.9838564 ],
       [ 0.89331562,  0.41423427,  0.33955778],
       [ 0.7705782 ,  0.73658281,  0.7741961 ]])

#### Samples from the standard normal distribution or Gaussian

In [25]:
np.random.randn(3)     # 하나만 쓰면 array로

array([ 0.28157185, -1.00552541,  0.78921549])

In [26]:
np.random.randn(2,2)  # Comma를 쓰면 matrix로

array([[-0.44749867,  0.77955126],
       [ 1.80418978,  0.98324492]])

#### Random integers from a low to a high

In [28]:
np.random.randint(1,100) # the low number is inclusive and the high is exclusive

9

In [29]:
np.random.randint(1,100,10)

array([48, 29, 30,  7, 70, 12, 28, 90, 93, 92])

# Reshape

In [31]:
arr=np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max(), min(), argmax(), argmin()

In [36]:
ranarr=np.random.randint(1,100,10)

In [37]:
ranarr

array([69, 59, 83, 30, 41, 78,  4, 20, 11, 26])

In [39]:
ranarr.max()

83

array에 속한 max 값 표시

In [40]:
ranarr.min()

4

array에 속한 min값 표시

In [41]:
ranarr.argmax()

2

array에서의 max값의 위치 표시

In [42]:
ranarr.argmin()

6

array에서의 min 값의 위치 표시

# Shape

In [43]:
arr.shape

(25,)

In [44]:
arrr = arr.reshape(5,5)

In [46]:
arrr.shape

(5, 5)

# Data type

In [47]:
arrr.dtype

dtype('int32')

In [48]:
arr.dtype

dtype('int32')

# Tips

np.random.randint가 다 쓰기 귀찮다면

In [50]:
from numpy.random import randint

In [1]:
randint(2,10)

NameError: name 'randint' is not defined

---
# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[2]

2

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[-1]

10

In [7]:
arr[-3]

8

Broadcast가 가능하단 점에서 python list와 numpy는 다르다.

In [8]:
arr[0:5]=100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr=np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr=arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:]=99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

arr을 불러오면 slice_of_arr만 바뀐 것이 아니라 original array였던 arr도 바뀌었음을 알 수 있다. <br>
slice_of_arr = arr[0:6]이 데이터가 copy되어 할당된 것이 아닌 단지 arr[0:6]부분을 view했음을 알 수 있다. <br>


In [17]:
arr_copy = arr.copy()

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:]=100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

copy method를 이처럼 써줘야지 original array에 영향을 받지 않는 copy가 만들어진다.

---
# Matrix (2D Array)

In [23]:
arr_2d=np.array([[5,10,15],[20,25,30],[30,40,45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

### * Double Bracket Format

In [25]:
arr_2d[0][0]

5

In [29]:
arr_2d[0]       # 0번째 행 선택

array([ 5, 10, 15])

### * Comma Single Bracket

In [30]:
arr_2d[1,2]

30

In [31]:
arr_2d[1][2]

30

In [32]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

2번째 행까지, 1번째 열부터

---
# Conditional Selection

In [33]:
arr=np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr>5 # return boolean value

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [37]:
bool_arr = arr>5

In [38]:
arr[bool_arr] #True인 것만 출력됐다.

array([ 6,  7,  8,  9, 10])

한 줄로 표현해 보자

In [39]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr<3]

array([1, 2])

---
## 연습

In [41]:
arr_2d2 = np.arange(50).reshape(5,10)

In [42]:
arr_2d2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

#### Q. 12, 13, 14를 불러와라

In [46]:
arr_2d2[1:2,2:4] # 1차 시기 실패

array([[12, 13]])

In [48]:
arr_2d2[1:3,2:4] # 2차 시기 실패

array([[12, 13],
       [22, 23]])

In [49]:
arr_2d2[1:2,2:5]

array([[12, 13, 14]])

성공!!!

---
# Numpy Operations

 * Array with Array
 * Array with Scalars
 * Universal Array Functions

In [50]:
import numpy as np

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [57]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [58]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

### Error 상황

In [59]:
1/0

ZeroDivisionError: division by zero

In [61]:
arr / arr # 첫번째는 0/0이였기 때문에 일반 python에선 에러가 떠야하지만 numpy는 그렇지 않음

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [62]:
1 / arr # 1/0은 0/0과는 다르게 inf를 돌려줌

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [63]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Universal Array Functions

In [64]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [65]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [66]:
np.max(arr)

10

In [69]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [70]:
np.min(arr)

0

In [83]:
np.log(arr)

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

---
# Axis

In [80]:
mat=np.arange(1,26).reshape(5,5)

In [86]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 모든 values의 합

In [85]:
mat.sum()

325

### 표준편차

In [87]:
mat.std()

7.2111025509279782

### Axis

In [89]:
mat.sum(axis=0)  # axis =0은 열

array([55, 60, 65, 70, 75])

In [91]:
mat.sum(axis=1)  # axis=1은 행

array([ 15,  40,  65,  90, 115])

In [92]:
mat.sum(axis =2) #당연히 2는 없지

ValueError: 'axis' entry is out of bounds

#### numpy 홈페이지 가서 많은 정보를 얻자